name: fresh_groceries_app
description: A Fresh Groceries App built using Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: "2.10.5"

dependencies:
  base:
    path: modules/base
  flutter:
    sdk: flutter
  get_it: 7.2.0
  home:
    path: features/home
  product:
    path: features/product
  shared_resources:
    path: modules/shared_resources

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter:
  uses-material-design: true
